// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Global → menu*
 */
export interface GlobalDocumentDataMenuItem {
  /**
   * link field in *Global → menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Global documents
 */
interface GlobalDocumentData {
  /**
   * logo field in *Global*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * logo footer field in *Global*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global.logo_footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_footer: prismic.ImageField<never>;

  /**
   * email field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField;

  /**
   * phone field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  phone: prismic.LinkField;

  /**
   * instagram field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * linkedin field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * privacy policy field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_policy: prismic.LinkField;

  /**
   * terms of use field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.terms_of_use
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  terms_of_use: prismic.LinkField;

  /**
   * menu field in *Global*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global.menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu: prismic.GroupField<Simplify<GlobalDocumentDataMenuItem>>;
}

/**
 * Global document from Prismic
 *
 * - **API ID**: `global`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalDocumentData>,
    "global",
    Lang
  >;

type PagesDocumentDataSlicesSlice =
  | BlockContactSlice
  | PersonalLifeSlice
  | AboutBlockSlice
  | EngageWIthMeSlice
  | TestimonialsSlice
  | CertifiedDistributionSlice
  | InsuranceBlockSlice
  | HeroSlice;

/**
 * Item in *pages → keywords*
 */
export interface PagesDocumentDataKeywordsItem {
  /**
   * title field in *pages → keywords*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.keywords[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Content for pages documents
 */
interface PagesDocumentData {
  /**
   * title field in *pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *pages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PagesDocumentDataSlicesSlice> /**
   * Meta Title field in *pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *pages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *pages*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.keywords[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  keywords: prismic.GroupField<Simplify<PagesDocumentDataKeywordsItem>>;
}

/**
 * pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PagesDocumentData>, "pages", Lang>;

export type AllDocumentTypes = GlobalDocument | PagesDocument;

/**
 * Primary content in *AboutBlock → Default → Primary*
 */
export interface AboutBlockSliceDefaultPrimary {
  /**
   * image field in *AboutBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *AboutBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *AboutBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for AboutBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutBlock*
 */
type AboutBlockSliceVariation = AboutBlockSliceDefault;

/**
 * AboutBlock Shared Slice
 *
 * - **API ID**: `about_block`
 * - **Description**: AboutBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutBlockSlice = prismic.SharedSlice<
  "about_block",
  AboutBlockSliceVariation
>;

/**
 * Primary content in *BlockContact → Default → Primary*
 */
export interface BlockContactSliceDefaultPrimary {
  /**
   * title field in *BlockContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *BlockContact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_contact.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for BlockContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlockContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlockContact*
 */
type BlockContactSliceVariation = BlockContactSliceDefault;

/**
 * BlockContact Shared Slice
 *
 * - **API ID**: `block_contact`
 * - **Description**: BlockContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContactSlice = prismic.SharedSlice<
  "block_contact",
  BlockContactSliceVariation
>;

/**
 * Primary content in *CertifiedDistribution → Default → Primary*
 */
export interface CertifiedDistributionSliceDefaultPrimary {
  /**
   * profile field in *CertifiedDistribution → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certified_distribution.default.primary.profile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile: prismic.ImageField<never>;

  /**
   * certified logo field in *CertifiedDistribution → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certified_distribution.default.primary.certified_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  certified_logo: prismic.ImageField<never>;

  /**
   * text field in *CertifiedDistribution → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certified_distribution.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * button text field in *CertifiedDistribution → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certified_distribution.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *CertifiedDistribution → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: certified_distribution.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkToMediaField;

  /**
   * right image field in *CertifiedDistribution → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certified_distribution.default.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_image: prismic.ImageField<never>;
}

/**
 * Default variation for CertifiedDistribution Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CertifiedDistributionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertifiedDistributionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CertifiedDistribution*
 */
type CertifiedDistributionSliceVariation = CertifiedDistributionSliceDefault;

/**
 * CertifiedDistribution Shared Slice
 *
 * - **API ID**: `certified_distribution`
 * - **Description**: CertifiedDistribution
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CertifiedDistributionSlice = prismic.SharedSlice<
  "certified_distribution",
  CertifiedDistributionSliceVariation
>;

/**
 * Primary content in *EngageWIthMe → Default → Primary*
 */
export interface EngageWIthMeSliceDefaultPrimary {
  /**
   * title 1 field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_1: prismic.KeyTextField;

  /**
   * title 2 field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * text field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * insta text field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.insta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  insta_text: prismic.KeyTextField;

  /**
   * instagram link field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.instagram_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_link: prismic.LinkToMediaField;

  /**
   * linked in text field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.linked_in_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linked_in_text: prismic.KeyTextField;

  /**
   * linkedin link field in *EngageWIthMe → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: engage_w_ith_me.default.primary.linkedin_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkToMediaField;
}

/**
 * Default variation for EngageWIthMe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EngageWIthMeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EngageWIthMeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EngageWIthMe*
 */
type EngageWIthMeSliceVariation = EngageWIthMeSliceDefault;

/**
 * EngageWIthMe Shared Slice
 *
 * - **API ID**: `engage_w_ith_me`
 * - **Description**: EngageWIthMe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EngageWIthMeSlice = prismic.SharedSlice<
  "engage_w_ith_me",
  EngageWIthMeSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * title 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkToMediaField;

  /**
   * button text 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * button link 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_2: prismic.LinkToMediaField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *InsuranceBlock → Default → Primary → columns*
 */
export interface InsuranceBlockSliceDefaultPrimaryColumnsItem {
  /**
   * title field in *InsuranceBlock → Default → Primary → columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance_block.default.primary.columns[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *InsuranceBlock → Default → Primary*
 */
export interface InsuranceBlockSliceDefaultPrimary {
  /**
   * title field in *InsuranceBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *InsuranceBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance_block.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * button text field in *InsuranceBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance_block.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *InsuranceBlock → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance_block.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkToMediaField;

  /**
   * columns field in *InsuranceBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: insurance_block.default.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  columns: prismic.GroupField<
    Simplify<InsuranceBlockSliceDefaultPrimaryColumnsItem>
  >;
}

/**
 * Default variation for InsuranceBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InsuranceBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InsuranceBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InsuranceBlock*
 */
type InsuranceBlockSliceVariation = InsuranceBlockSliceDefault;

/**
 * InsuranceBlock Shared Slice
 *
 * - **API ID**: `insurance_block`
 * - **Description**: InsuranceBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InsuranceBlockSlice = prismic.SharedSlice<
  "insurance_block",
  InsuranceBlockSliceVariation
>;

/**
 * Item in *PersonalLife → Default → Primary → images*
 */
export interface PersonalLifeSliceDefaultPrimaryImagesItem {
  /**
   * image field in *PersonalLife → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_life.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *PersonalLife → Default → Primary*
 */
export interface PersonalLifeSliceDefaultPrimary {
  /**
   * title field in *PersonalLife → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_life.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *PersonalLife → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_life.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * images field in *PersonalLife → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: personal_life.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<PersonalLifeSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for PersonalLife Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PersonalLifeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PersonalLifeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PersonalLife*
 */
type PersonalLifeSliceVariation = PersonalLifeSliceDefault;

/**
 * PersonalLife Shared Slice
 *
 * - **API ID**: `personal_life`
 * - **Description**: PersonalLife
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PersonalLifeSlice = prismic.SharedSlice<
  "personal_life",
  PersonalLifeSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * image field in *Testimonials → Default → Primary → testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Testimonials → Default → Primary → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * position field in *Testimonials → Default → Primary → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * content field in *Testimonials → Default → Primary → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GlobalDocument,
      GlobalDocumentData,
      GlobalDocumentDataMenuItem,
      PagesDocument,
      PagesDocumentData,
      PagesDocumentDataSlicesSlice,
      PagesDocumentDataKeywordsItem,
      AllDocumentTypes,
      AboutBlockSlice,
      AboutBlockSliceDefaultPrimary,
      AboutBlockSliceVariation,
      AboutBlockSliceDefault,
      BlockContactSlice,
      BlockContactSliceDefaultPrimary,
      BlockContactSliceVariation,
      BlockContactSliceDefault,
      CertifiedDistributionSlice,
      CertifiedDistributionSliceDefaultPrimary,
      CertifiedDistributionSliceVariation,
      CertifiedDistributionSliceDefault,
      EngageWIthMeSlice,
      EngageWIthMeSliceDefaultPrimary,
      EngageWIthMeSliceVariation,
      EngageWIthMeSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InsuranceBlockSlice,
      InsuranceBlockSliceDefaultPrimaryColumnsItem,
      InsuranceBlockSliceDefaultPrimary,
      InsuranceBlockSliceVariation,
      InsuranceBlockSliceDefault,
      PersonalLifeSlice,
      PersonalLifeSliceDefaultPrimaryImagesItem,
      PersonalLifeSliceDefaultPrimary,
      PersonalLifeSliceVariation,
      PersonalLifeSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
