// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_block: dynamic(() => import("./AboutBlock")),
  certified_distribution: dynamic(() => import("./CertifiedDistribution")),
  engage_w_ith_me: dynamic(() => import("./EngageWIthMe")),
  hero: dynamic(() => import("./Hero")),
  insurance_block: dynamic(() => import("./InsuranceBlock")),
  personal_life: dynamic(() => import("./PersonalLife")),
  testimonials: dynamic(() => import("./Testimonials")),
};
